version: 3

dotenv:
  - .env

vars:
  VERSION:
    sh: git describe --always --dirty --tags

tasks:
  default:
    deps: [backend]
    cmds:
      - ./backend.exe
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - app/**/*.go

  production:
    cmds:
      - ./backend.exe

  backend:
    cmds:
      - go build -o backend.exe -ldflags="-X 'github.com/Southclaws/storyden/internal/config.Version={{.VERSION}}'" ./cmd/backend
  backend:test:
    cmds:
      - go test -p 1 -race ./...

  backend:image:
    cmds:
      - docker build -t {{.DOCKER_IMAGE_TAG}} .

  # -
  # Code generation
  # -

  generate:
    deps: [generate:db, generate:openapi]

  generate:db:
    cmds:
      - go generate ./internal/infrastructure/db/...

  generate:openapi:
    cmds:
      - oapi-codegen --config ./api/config.yaml ./api/openapi.yaml

  # -
  # Database
  # -

  db:migrate:
    cmds:
      - go run ./tools/migrate {{.CLI_ARGS}}

  db:ui:
    cmds:
      - atlas schema inspect -d {{.DATABASE_URL}} -w
