version: 3

vars:
  VERSION:
    sh: git describe --always --dirty --tags
  LOCAL_DB: postgres://default:default@localhost:5432/postgres?sslmode=disable

tasks:
  default:
    deps: [backend]
    cmds:
      - ./backend.exe
    sources:
      - cmd/**/*.go
      - internal/**/*.go
      - pkg/**/*.go

  production:
    cmds:
      - ./backend.exe

  backend:
    cmds:
      - go build -o backend.exe -ldflags="-X 'github.com/Southclaws/storyden/internal/config.Version={{.VERSION}}'" ./cmd/api
  backend:test:
    cmds:
      - go test -p 1 -race ./...

  backend:image:
    cmds:
      - docker build -t {{.DOCKER_IMAGE_TAG}} .

  # -
  # Code generation
  # -

  generate:
    deps: [generate:db, generate:openapi]

  generate:db:
    cmds:
      - go generate ./internal/infrastructure/db/...

  generate:openapi:
    cmds:
      - oapi-codegen --config ./api/config.yaml ./api/openapi.yaml

  # -
  # Database
  # -

  db:migrate:
    deps: [db:migrate:generate, db:migrate:run]

  db:migrate:generate:
    desc: Generate migrations from schema changes.
    cmds:
      - go run ./cmd/generate/main.go

  db:migrate:run:
    desc: Execute migrations against database.
    cmds:
      - go run ./cmd/migrate/main.go

  db:ui:
    cmds:
      - atlas schema inspect -d {{.LOCAL_DB}} -w
