openapi: 3.0.1

info:
  title: storyden
  version: "1"

security:
  - cookieAuth: []

paths:
  /version:
    get:
      security: []
      operationId: getVersion
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /openapi.json:
    get:
      security: []
      operationId: getSpec
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string

  /v1/auth/password/signup:
    post:
      operationId: signup
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIError"

  /v1/auth/password/signin:
    post:
      operationId: signin
      requestBody:
        content:
          application/x-www-form-urlencoded,application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
      responses:
        200:
          description: OK
        404:
          description: User not found
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/APIError"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: storyden-session

  schemas:
    AuthenticationRequest:
      type: object
      properties:
        identifier:
          required:
            - ""
          type: string
        token:
          type: string

    APIError:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        suggested:
          type: string
