openapi: 3.0.1

#
#            ╓███,
#          ▄██▀"███▄
#         ╚█▀    `▀██▄
#     ,,     ╓███,  ▀██▌_
#   ╓███   ▄██▀"███▄  ╙███_
#  ▐██"  ▄██▀    `▀██▄  ╙██
#  ▐██  ╙██▄       ╫██Γ  ██─
#  ▐██    ▀██▄  ,▓██▀    ██─
#  ▐██      ╙█████▀      ██─
#  ▐██      ╓█████_      ██─
#  ▐██    ▄██▀` ╙███╥    ██─
#  └███████▀      `▀██   ██
#

info:
  title: storyden
  version: "1"

servers:
  - url: "/api"

security:
  - browser: []

#
# 8888888b.     d8888 88888888888 888    888  .d8888b.
# 888   Y88b   d88888     888     888    888 d88P  Y88b
# 888    888  d88P888     888     888    888 Y88b.
# 888   d88P d88P 888     888     8888888888  "Y888b.
# 8888888P" d88P  888     888     888    888     "Y88b.
# 888      d88P   888     888     888    888       "888
# 888     d8888888888     888     888    888 Y88b  d88P
# 888    d88P     888     888     888    888  "Y8888P"
#

paths:
  #
  #                d8b
  #                Y8P
  #
  #  88888b.d88b.  888 .d8888b   .d8888b
  #  888 "888 "88b 888 88K      d88P"
  #  888  888  888 888 "Y8888b. 888
  #  888  888  888 888      X88 Y88b.
  #  888  888  888 888  88888P'  "Y8888P
  #

  /version:
    get:
      security: []
      operationId: getVersion
      tags: [misc]
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string

  /openapi.json:
    get:
      security: []
      operationId: getSpec
      tags: [misc]
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string

  #
  #                   888    888
  #                   888    888
  #                   888    888
  #  8888b.  888  888 888888 88888b.
  #     "88b 888  888 888    888 "88b
  # .d888888 888  888 888    888  888
  # 888  888 Y88b 888 Y88b.  888  888
  # "Y888888  "Y88888  "Y888 888  888
  #

  /v1/auth/password/signup:
    post:
      operationId: signup
      tags: [auth]
      security: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
      responses:
        default: { "$ref": "#/components/responses/InternalServerError" }
        400: { "$ref": "#/components/responses/BadRequest" }
        200: { "$ref": "#/components/responses/AuthenticationSuccess" }

  /v1/auth/password/signin:
    post:
      operationId: signin
      tags: [auth]
      security: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
      responses:
        default: { "$ref": "#/components/responses/InternalServerError" }
        404: { "$ref": "#/components/responses/NotFound" }
        401: { "$ref": "#/components/responses/Unauthorised" }
        200: { "$ref": "#/components/responses/AuthenticationSuccess" }

  #
  #                                                      888
  #                                                      888
  #                                                      888
  #   8888b.   .d8888b .d8888b .d88b.  888  888 88888b.  888888 .d8888b
  #      "88b d88P"   d88P"   d88""88b 888  888 888 "88b 888    88K
  #  .d888888 888     888     888  888 888  888 888  888 888    "Y8888b.
  #  888  888 Y88b.   Y88b.   Y88..88P Y88b 888 888  888 Y88b.       X88
  #  "Y888888  "Y8888P "Y8888P "Y88P"   "Y88888 888  888  "Y888  88888P'
  #

  /v1/accounts/{id}:
    get:
      operationId: getAccount
      tags: [accounts]
      security:
        - browser: []
      parameters:
        - name: id
          in: path
          description: Account ID
          required: true
          schema:
            $ref: "#/components/schemas/Identifier"
      responses:
        default: { "$ref": "#/components/responses/InternalServerError" }
        404: { "$ref": "#/components/responses/NotFound" }
        401: { "$ref": "#/components/responses/Unauthorised" }
        200: { "$ref": "#/components/responses/GetAccountSuccess" }

  #
  # 888    888                                    888
  # 888    888                                    888
  # 888    888                                    888
  # 888888 88888b.  888d888 .d88b.   8888b.   .d88888 .d8888b
  # 888    888 "88b 888P"  d8P  Y8b     "88b d88" 888 88K
  # 888    888  888 888    88888888 .d888888 888  888 "Y8888b.
  # Y88b.  888  888 888    Y8b.     888  888 Y88b 888      X88
  #  "Y888 888  888 888     "Y8888  "Y888888  "Y88888  88888P'
  #

  /v1/threads:
    post:
      operationId: createThread
      tags: [threads]
      security:
        - browser: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/ThreadSubmission"
          application/json:
            schema:
              $ref: "#/components/schemas/ThreadSubmission"

      responses:
        default: { "$ref": "#/components/responses/InternalServerError" }
        404: { "$ref": "#/components/responses/NotFound" }
        401: { "$ref": "#/components/responses/Unauthorised" }
        200: { "$ref": "#/components/responses/CreateThreadSuccess" }

  #
  #                             888
  #                             888
  #                             888
  #  88888b.   .d88b.  .d8888b  888888 .d8888b
  #  888 "88b d88""88b 88K      888    88K
  #  888  888 888  888 "Y8888b. 888    "Y8888b.
  #  888 d88P Y88..88P      X88 Y88b.       X88
  #  88888P"   "Y88P"   88888P'  "Y888  88888P'
  #  888
  #  888
  #  888
  #

components:
  #
  # 8888888b.  8888888888 .d8888b.  8888888b.   .d88888b.  888b    888  .d8888b.  8888888888 .d8888b.
  # 888   Y88b 888       d88P  Y88b 888   Y88b d88P" "Y88b 8888b   888 d88P  Y88b 888       d88P  Y88b
  # 888    888 888       Y88b.      888    888 888     888 88888b  888 Y88b.      888       Y88b.
  # 888   d88P 8888888    "Y888b.   888   d88P 888     888 888Y88b 888  "Y888b.   8888888    "Y888b.
  # 8888888P"  888           "Y88b. 8888888P"  888     888 888 Y88b888     "Y88b. 888           "Y88b.
  # 888 T88b   888             "888 888        888     888 888  Y88888       "888 888             "888
  # 888  T88b  888       Y88b  d88P 888        Y88b. .d88P 888   Y8888 Y88b  d88P 888       Y88b  d88P
  # 888   T88b 8888888888 "Y8888P"  888         "Y88888P"  888    Y888  "Y8888P"  8888888888 "Y8888P"
  #

  responses:
    BadRequest:
      description: Bad request
    NotFound:
      description: Not found
    Unauthorised:
      description: Unauthorized
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIError"

    AuthenticationSuccess:
      description: OK
      headers:
        "Set-Cookie":
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AuthenticationSuccess"

    GetAccountSuccess:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Account"

    CreateThreadSuccess:
      description: Thread created.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Thread"

  #
  #  .d8888b.   .d8888b.  888    888 8888888888 888b     d888        d8888  .d8888b.
  # d88P  Y88b d88P  Y88b 888    888 888        8888b   d8888       d88888 d88P  Y88b
  # Y88b.      888    888 888    888 888        88888b.d88888      d88P888 Y88b.
  #  "Y888b.   888        8888888888 8888888    888Y88888P888     d88P 888  "Y888b.
  #     "Y88b. 888        888    888 888        888 Y888P 888    d88P  888     "Y88b.
  #       "888 888    888 888    888 888        888  Y8P  888   d88P   888       "888
  # Y88b  d88P Y88b  d88P 888    888 888        888   "   888  d8888888888 Y88b  d88P
  #  "Y8888P"   "Y8888P"  888    888 8888888888 888       888 d88P     888  "Y8888P"
  #

  schemas:
    Identifier:
      type: string
      format: xid
      x-go-type: xid.ID
      x-go-type-import:
        name: xid
        path: github.com/rs/xid
      example: "cc5lnd2s1s4652adtu50"
      description: A unique identifier for this resource.

    CommonProperties:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
        createdAt:
          type: string
          format: date-time
          description: The time the resource was created.
        updatedAt:
          type: string
          format: date-time
          description: The time the resource was updated.
        deletedAt:
          type: string
          format: date-time
          description: The time the resource was soft-deleted.

    APIError:
      type: object
      description: A description of an error including a human readable message.
      required: [error]
      properties:
        error:
          type: string
        message:
          type: string
        suggested:
          type: string

    AuthenticationRequest:
      type: object
      required: [identifier, token]
      properties:
        identifier:
          example: "southclaws@storyden.org"
          type: string
        token:
          example: "password"
          type: string

    AuthenticationSuccess:
      type: object
      required: [id]
      properties:
        id:
          type: string

    Account:
      type: object
      required: [id]
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
        email:
          type: string
        name:
          type: string
        bio:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string

    ThreadSubmission:
      type: object
      required:
        - title
        - body
        - tags
        - category
      properties:
        title:
          type: string
          example: Hello world!
          description: The title of the thread.
        body:
          type: string
          description: The markdown body for the new thread.
        tags:
          type: array
          items:
            type: string
          description: A list of tags for the new thread.
        category:
          $ref: "#/components/schemas/Identifier"

    Thread:
      allOf:
        - $ref: "#/components/schemas/CommonProperties"
        - type: object
          required:
            - id
            - createdAt
            - updatedAt
            - title
            - slug
            - short
          properties:
            title:
              type: string
              example: Hello world!
              description: The title of the thread.
            slug:
              type: string
              readOnly: true
              description: |
                A URL friendly slug which is prepended with the post ID
                for uniqueness and sortability.
            short:
              type: string
              readOnly: true
              description: |
                A short version of the thread's body text for use in previews.
            pinned:
              type: boolean
              description: Whether the thread is pinned in this category.
            author:
              $ref: "#/components/schemas/ProfileReference"
              readOnly: true
            tags:
              type: array
              items:
                type: string
              description: A list of tags associated with the thread.
            posts:
              type: integer
              readOnly: true
              description: The number of posts under this thread.
            category:
              $ref: "#/components/schemas/Category"
            reacts:
              type: array
              items:
                $ref: "#/components/schemas/React"
              description: A list of reactions this post has had from people.

    ProfileReference:
      type: object
      description: A minimal reference to an account.
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
        name:
          type: string

    Category:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
        name:
          type: string
        description:
          type: string
        colour:
          type: string
        sort:
          type: integer
        admin:
          type: boolean
        postCount:
          type: integer

    React:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
        emoji:
          type: string

  securitySchemes:
    browser:
      type: apiKey
      in: cookie
      name: storyden-session
#
#     ..:.                                                        .***=
#  .+#%%%%%#+   ...                                               :%%%+
#  #%%%+==+#.  =%%%.                                              :%%%+
# :%%%%:      -*%%%=-.   :==+==:    ---: :== ----     .---- .-===-:%%%+   :==+=-:   .---..-==-.
#  +%%%%%#*=. #%%%%%%-.+%%%%#%%%%+ .%%%##%%% -%%%#.  .#%%#=*%%%%%%%%%%+ =%%#+=+#%#- -%%%#%#%%%%*
#   .-+#%%%%%- +%%%:..#%%%=   +%%%*.%%%#-. .  :#%%#..#%%#:#%%%=  .+%%%+-%%%*===+%%%:-%%%+  .#%%%.
#        +%%%# =%%%. .%%%#    .%%%%.%%%+       .#%%##%%#:.%%%#    :%%%+=%%%*+++++++:-%%%:   +%%%.
# .##*===#%%%= =%%%.  +%%%#=-=#%%%-.%%%+        .#%%%%*.  +%%%#=-=#%%%+.#%%+:..=++= -%%%:   +%%%.
# -*%%%%%%%*-  =%%%.   :*%%%%%%#+: .%%%+         -%%%#.    -*%%%%%*%%%+ .+#%%%%%%+. -%%%:   +%%%.
#    .:::.                .:::.                 -%%%*.        .:.          .:::.
#                                              -%%%*
#                                             -***+
#
