name: Test backend

on:
  push:

jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: default
          POSTGRES_PASSWORD: default
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: "postgresql://default:default@postgres:5432/postgres"

    steps:
      - uses: actions/checkout@v2

      - name: Setup go-task/task
        uses: lukeshay/setup-task@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: task backend

      - name: Test
        run: task backend:test
