name: Test backend

on:
  push:

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup go-task/task
        uses: wizhi/setup-task@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: task backend

      - name: Test
        run: task backend:test
